// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMenu is the golang structure for table admin_menu.
type AdminMenu struct {
	Id                 uint        `json:"id"                   ` //
	Name               string      `json:"name"                 ` // 菜单名称
	Path               string      `json:"path"                 ` // 请求后端路径，可以是外链
	ParentId           int         `json:"parent_id"            ` // 父id
	Identification     string      `json:"identification"       ` // 权限标识符
	FrontComponentPath string      `json:"front_component_path" ` // 前端组件路径
	Icon               string      `json:"icon"                 ` // 菜单图标
	Sort               int         `json:"sort"                 ` // 显示顺序，越小越靠前
	Status             string      `json:"status"               ` // 状态 normal 正常 disabled 禁用
	CreatedAt          *gtime.Time `json:"created_at"           ` // 创建时间
	UpdatedAt          *gtime.Time `json:"updated_at"           ` // 更新时间
}

// Administrator is the golang structure for table administrator.
type Administrator struct {
	Id            uint        `json:"id"              ` //
	Username      string      `json:"username"        ` // 用户名
	Password      string      `json:"password"        ` // MD5密码
	Nickname      string      `json:"nickname"        ` // 昵称
	Avatar        string      `json:"avatar"          ` // 头像地址
	Status        string      `json:"status"          ` // 状态 normal 正常 disabled 禁用
	Remark        string      `json:"remark"          ` // 备注
	LastLoginIp   string      `json:"last_login_ip"   ` // 最后登陆IP
	LastLoginDate *gtime.Time `json:"last_login_date" ` // 最后登陆时间
	CreatedAt     *gtime.Time `json:"created_at"      ` // 注册时间
	UpdatedAt     *gtime.Time `json:"updated_at"      ` // 更新时间
}

// AdministratorRole is the golang structure for table administrator_role.
type AdministratorRole struct {
	Id              uint        `json:"id"               ` //
	AdministratorId int         `json:"administrator_id" ` // 管理员id
	RoleId          int         `json:"role_id"          ` // 角色id
	CreatedAt       *gtime.Time `json:"created_at"       ` // 创建时间
	UpdatedAt       *gtime.Time `json:"updated_at"       ` // 更新时间
}

// Role is the golang structure for table role.
type Role struct {
	Id             uint        `json:"id"             ` //
	Name           string      `json:"name"           ` // 角色名
	Identification string      `json:"identification" ` // 角色标识符
	Sort           int         `json:"sort"           ` // 显示顺序，越小越靠前
	Status         string      `json:"status"         ` // 状态 normal 正常 disabled 禁用
	CreatedAt      *gtime.Time `json:"created_at"     ` // 创建时间
	UpdatedAt      *gtime.Time `json:"updated_at"     ` // 更新时间
}
