// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Collects is the golang structure for table collects.
type Collects struct {
	Id              uint        `json:"id"               ` // ID
	Symbol          string      `json:"symbol"           ` // 代币符号
	ContractAddress string      `json:"contract_address" ` //
	UserId          int         `json:"user_id"          ` // 用户id
	UserAddress     string      `json:"user_address"     ` // 用户地址
	RechargeHash    string      `json:"recharge_hash"    ` // 充值hash
	HandfeeHash     string      `json:"handfee_hash"     ` // 手续费hash
	CollectHash     string      `json:"collect_hash"     ` // 归集hash
	Value           string      `json:"value"            ` // 归集金额
	RechargeValue   string      `json:"recharge_value"   ` // 充值金额
	Status          string      `json:"status"           ` // 状态 fail 失败，wait_fee 待转手续费，process_fee 转手续费中，wait_collect 待归集,process_wait归集中，wait_notify 待通知,finish_notify通知完成
	CreateAt        *gtime.Time `json:"create_at"        ` // 创建时间
	UpdateAt        *gtime.Time `json:"update_at"        ` // 更新时间
}
