// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// HealthRecord is the golang structure for table health_record.
type HealthRecord struct {
	Id             uint        `json:"id"              ` //
	Day            *gtime.Time `json:"day"             ` // 当前日期
	Breakfast      string      `json:"breakfast"       ` // 早餐,json格式,{type:事务名称,is_later:是否晚点,has_meat:是否含肉}
	Launch         string      `json:"launch"          ` // 早餐,json格式,{type:事务名称,is_later:是否晚点,has_meat:是否含肉}
	Dinner         string      `json:"dinner"          ` // 中餐,json格式,json格式,{type:事务名称,is_later:是否晚点,has_meat:是否含肉}
	Drink          string      `json:"drink"           ` // 饮料,json格式,{coffee_americano:没事咖啡,coffee_latte:拿铁,drink_mix_sang:西洋参等,drink_cold:冷饮,additional:其他附加的饮料}
	Sleep          string      `json:"sleep"           ` // 睡眠,json格式,{start:开始时间,end:结束时间}
	Run            string      `json:"run"             ` // 运动,json格式,{time:运动时间,distance:运动距离,is_nausea:是否反胃}
	Stomach        string      `json:"stomach"         ` // 胃,json格式,{stomachache_level:疼痛级别(0正常，1隐痛，2轻微疼痛，3较重疼痛，4重度疼痛),is_nausea:非运动是否恶心}
	Tongue         string      `json:"tongue"          ` // 舌,json格式,{is_thick_ease:舌苔后是否缓解,is_dry:舌苔是否干燥}
	DefecateAmount uint        `json:"defecate_amount" ` // 排便次数
	FartIsMuch     uint        `json:"fart_is_much"    ` // 放屁是否频繁
	HasNewAcne     uint        `json:"has_new_acne"    ` // 是否有新的痤疮
	CreatedAt      *gtime.Time `json:"created_at"      ` // 创建时间
	UpdatedAt      *gtime.Time `json:"updated_at"      ` // 更新时间
}
