// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// LoseBlocks is the golang structure for table lose_blocks.
type LoseBlocks struct {
	Id       int         `json:"id"        ` //
	Number   int         `json:"number"    ` // 区块号
	Status   int         `json:"status"    ` // 检测状态，1已检测，0未检测
	CreateAt *gtime.Time `json:"create_at" ` // 创建时间
	UpdateAt *gtime.Time `json:"update_at" ` // 更新时间
}
