// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Networks is the golang structure for table networks.
type Networks struct {
	Id       int         `json:"id"        ` //
	Url      string      `json:"url"       ` // 请求地址
	Name     string      `json:"name"      ` // 网络名称
	ChainId  int         `json:"chain_id"  ` //
	IsUse    int         `json:"is_use"    ` // 是否是正在使用的网络
	CreateAt *gtime.Time `json:"create_at" ` // 创建时间
	UpdateAt *gtime.Time `json:"update_at" ` // 更新时间
}
