// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// NotifyLog is the golang structure for table notify_log.
type NotifyLog struct {
	Id         uint        `json:"id"          ` // ID
	NotifyId   int         `json:"notify_id"   ` // notify id
	Log        string      `json:"log"         ` // 错误日志
	FailAmount int         `json:"fail_amount" ` // 第几次失败
	CreateAt   *gtime.Time `json:"create_at"   ` // 创建时间
	UpdateAt   *gtime.Time `json:"update_at"   ` // 更新时间
}
