// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Notify is the golang structure for table notify.
type Notify struct {
	Id                 uint        `json:"id"                   ` // ID
	Type               string      `json:"type"                 ` // 交易类型, recharge 充值，withdraw 提现
	RelationId         uint        `json:"relation_id"          ` // 关联表id
	NotifyData         string      `json:"notify_data"          ` // 通知数据
	NotifyAddress      string      `json:"notify_address"       ` // 通知地址
	UniqueId           string      `json:"unique_id"            ` // 唯一id
	FailAmount         int         `json:"fail_amount"          ` // 失败次数
	Status             string      `json:"status"               ` // 状态 fail 失败,wait等待通知  finish通知完成
	IsImmediatelyRetry int         `json:"is_immediately_retry" ` // 是否立即重试
	CreateAt           *gtime.Time `json:"create_at"            ` // 创建时间
	NotifyAt           *gtime.Time `json:"notify_at"            ` // 上次通知时间
}
