// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// QueueTask is the golang structure for table queue_task.
type QueueTask struct {
	Id              int         `json:"id"               ` //
	Hash            string      `json:"hash"             ` //
	Symbol          string      `json:"symbol"           ` //
	ContractAddress string      `json:"contract_address" ` //
	From            string      `json:"from"             ` // 转出地址
	To              string      `json:"to"               ` // 转入地址
	Value           string      `json:"value"            ` // 金额
	GasLimit        int         `json:"gas_limit"        ` // gas  限制
	GasPrice        string      `json:"gas_price"        ` // gas 预估 价格
	ActualGasUsed   int         `json:"actual_gas_used"  ` // gas 实际消耗
	ActualGasPrice  string      `json:"actual_gas_price" ` // gas 实际价格
	ActualFee       string      `json:"actual_fee"       ` // 实际手续费
	Nonce           int         `json:"nonce"            ` //
	Type            string      `json:"type"             ` // 交易类型
	Status          string      `json:"status"           ` // 转账状态: fail 转出失败,wait 等待转出,process 转出中,success转出成功
	FailAmount      int         `json:"fail_amount"      ` // 失败次数
	PrivateKey      string      `json:"private_key"      ` // 私钥
	RelationId      uint        `json:"relation_id"      ` // 关联的其他表id
	CreateAt        *gtime.Time `json:"create_at"        ` // 创建时间
	SendAt          *gtime.Time `json:"send_at"          ` // 发送转账时间
	FinishAt        *gtime.Time `json:"finish_at"        ` // 转账检测成功时间
	UpdateAt        *gtime.Time `json:"update_at"        ` // 更新时间
}
