// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure for table _users.
type Users struct {
	Id                  uint        `json:"id"                     ` //
	Username            string      `json:"username"               ` // 用户名
	Email               string      `json:"email"                  ` // email
	Description         string      `json:"description"            ` // 简介
	Password            string      `json:"password"               ` // MD5密码
	Avatar              string      `json:"avatar"                 ` // 头像地址
	Status              string      `json:"status"                 ` // 状态：disable_login | disable_posts | disable_reply
	PostsAmount         uint        `json:"posts_amount"           ` // 创建主题次数
	ReplyAmount         uint        `json:"reply_amount"           ` // 回复次数
	ShieldedAmount      uint        `json:"shielded_amount"        ` // 被屏蔽次数
	FollowByOtherAmount uint        `json:"follow_by_other_amount" ` // 被关注次数
	TodayActivity       uint        `json:"today_activity"         ` // 今日活跃度
	Balance             uint64      `json:"balance"                ` // 余额
	Remark              string      `json:"remark"                 ` // 备注
	LastLoginIp         string      `json:"last_login_ip"          ` // 最后登陆IP
	LastLoginTime       *gtime.Time `json:"last_login_time"        ` // 最后登陆时间
	CreatedAt           *gtime.Time `json:"created_at"             ` // 注册时间
	UpdatedAt           *gtime.Time `json:"updated_at"             ` // 更新时间
	DeletedAt           *gtime.Time `json:"deleted_at"             ` // 删除时间
}
