// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserAddresses is the golang structure for table user_addresses.
type UserAddresses struct {
	Id             uint        `json:"id"               ` // ID
	Address        string      `json:"address"          ` // 以太坊地址
	ExternalUserId string      `json:"external_user_id" ` // 外部用户id
	PrivateKey     string      `json:"private_key"      ` // 私钥
	Type           int         `json:"type"             ` // 类型:0平台生成,1外部导入
	CreateAt       *gtime.Time `json:"create_at"        ` // 创建时间
	UpdateAt       *gtime.Time `json:"update_at"        ` // 更新时间
}
