// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Collects is the golang structure of table collects for DAO operations like Where/Data.
type Collects struct {
	g.Meta          `orm:"table:collects, do:true"`
	Id              interface{} // ID
	Symbol          interface{} // 代币符号
	ContractAddress interface{} //
	UserId          interface{} // 用户id
	UserAddress     interface{} // 用户地址
	RechargeHash    interface{} // 充值hash
	HandfeeHash     interface{} // 手续费hash
	CollectHash     interface{} // 归集hash
	Value           interface{} // 归集金额
	RechargeValue   interface{} // 充值金额
	Status          interface{} // 状态 fail 失败，wait_fee 待转手续费，process_fee 转手续费中，wait_collect 待归集,process_wait归集中，wait_notify 待通知,finish_notify通知完成
	CreateAt        *gtime.Time // 创建时间
	UpdateAt        *gtime.Time // 更新时间
}
