// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Contracts is the golang structure of table contracts for DAO operations like Where/Data.
type Contracts struct {
	g.Meta        `orm:"table:contracts, do:true"`
	Id            interface{} //
	Symbol        interface{} // 货币类型
	Address       interface{} // 合约地址
	Decimals      interface{} // 小数位数
	IsCollectOpen interface{} // 是否开启,1是 0否
	CreateAt      *gtime.Time // 创建时间
	UpdateAt      *gtime.Time // 更新时间
}
