// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FollowOrShieldUserRelation is the golang structure of table forum_follow_or_shield_user_relation for DAO operations like Where/Data.
type FollowOrShieldUserRelation struct {
	g.Meta         `orm:"table:forum_follow_or_shield_user_relation, do:true"`
	Id             interface{} //
	UserId         interface{} // 用户id
	Username       interface{} // 用户名
	TargetUserId   interface{} // 被关注｜屏蔽用户id
	TargetUsername interface{} // 被关注｜屏蔽用户名
	Type           interface{} // 类型 关注: follow,屏蔽: shield
	CreatedAt      *gtime.Time // 创建时间
}
