// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// LoseBlocks is the golang structure of table lose_blocks for DAO operations like Where/Data.
type LoseBlocks struct {
	g.Meta   `orm:"table:lose_blocks, do:true"`
	Id       interface{} //
	Number   interface{} // 区块号
	Status   interface{} // 检测状态，1已检测，0未检测
	CreateAt *gtime.Time // 创建时间
	UpdateAt *gtime.Time // 更新时间
}
