// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Nodes is the golang structure of table forum_nodes for DAO operations like Where/Data.
type Nodes struct {
	g.Meta      `orm:"table:forum_nodes, do:true"`
	Id          interface{} //
	Name        interface{} // 节点名称
	Description interface{} // 节点描述
	IsIndex     interface{} // 是否首页显示
	IsCanEdit   interface{} // 是否允许编辑
	CreatedAt   *gtime.Time // 创建时间
	DeletedAt   *gtime.Time // 删除时间
}
