// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// QueueTask is the golang structure of table queue_task for DAO operations like Where/Data.
type QueueTask struct {
	g.Meta          `orm:"table:queue_task, do:true"`
	Id              interface{} //
	Hash            interface{} //
	Symbol          interface{} //
	ContractAddress interface{} //
	From            interface{} // 转出地址
	To              interface{} // 转入地址
	Value           interface{} // 金额
	GasLimit        interface{} // gas  限制
	GasPrice        interface{} // gas 预估 价格
	ActualGasUsed   interface{} // gas 实际消耗
	ActualGasPrice  interface{} // gas 实际价格
	ActualFee       interface{} // 实际手续费
	Nonce           interface{} //
	Type            interface{} // 交易类型
	Status          interface{} // 转账状态: fail 转出失败,wait 等待转出,process 转出中,success转出成功
	FailAmount      interface{} // 失败次数
	PrivateKey      interface{} // 私钥
	RelationId      interface{} // 关联的其他表id
	CreateAt        *gtime.Time // 创建时间
	SendAt          *gtime.Time // 发送转账时间
	FinishAt        *gtime.Time // 转账检测成功时间
	UpdateAt        *gtime.Time // 更新时间
}
