// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ThanksOrShieldOrCollectContentRelation is the golang structure of table forum_thanks_or_shield_or_collect_content_relation for DAO operations like Where/Data.
type ThanksOrShieldOrCollectContentRelation struct {
	g.Meta         `orm:"table:forum_thanks_or_shield_or_collect_content_relation, do:true"`
	Id             interface{} //
	UserId         interface{} // 用户id
	Username       interface{} // 用户名
	TargetId       interface{} // 被感谢｜屏蔽|收藏 主题id|回复id
	TargetUserId   interface{} // 被感谢｜屏蔽|收藏 用户id
	TargetUsername interface{} // 被感谢用户名
	Type           interface{} // 类型 感谢主题: thanks_posts,感谢回复: thanks_reply,屏蔽主题: shield_posts,屏蔽回复: shield_reply,收藏主题:collect_posts
	CreatedAt      *gtime.Time // 创建时间
}
