// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserAddresses is the golang structure of table user_addresses for DAO operations like Where/Data.
type UserAddresses struct {
	g.Meta         `orm:"table:user_addresses, do:true"`
	Id             interface{} // ID
	Address        interface{} // 以太坊地址
	ExternalUserId interface{} // 外部用户id
	PrivateKey     interface{} // 私钥
	Type           interface{} // 类型:0平台生成,1外部导入
	CreateAt       *gtime.Time // 创建时间
	UpdateAt       *gtime.Time // 更新时间
}
