// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Withdraws is the golang structure of table withdraws for DAO operations like Where/Data.
type Withdraws struct {
	g.Meta          `orm:"table:withdraws, do:true"`
	Id              interface{} // ID
	UserId          interface{} // 内部用户id
	ExternalOrderId interface{} // 外部订单id
	ExternalUserId  interface{} // 外部用户id
	Hash            interface{} // hash
	Symbol          interface{} // 代币符号
	ContractAddress interface{} //
	From            interface{} // 转出地址
	To              interface{} // 转入地址
	Value           interface{} // 转出金额
	Status          interface{} // 状态 fail 失败，wait 待转出，process 转出中，wait_notify转出完成,finish_notify通知完成
	CreateAt        *gtime.Time // 创建时间
	UpdateAt        *gtime.Time // 更新时间
}
