// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalCollectsDao is internal type for wrapping internal DAO implements.
type internalCollectsDao = *internal.CollectsDao

// collectsDao is the data access object for table collects.
// You can define custom methods on it to extend its functionality as you wish.
type collectsDao struct {
	internalCollectsDao
}

var (
	// Collects is globally public accessible object for table collects operations.
	Collects = collectsDao{
		internal.NewCollectsDao(),
	}
)

// Fill with you ideas below.
