// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalContractsDao is internal type for wrapping internal DAO implements.
type internalContractsDao = *internal.ContractsDao

// contractsDao is the data access object for table contracts.
// You can define custom methods on it to extend its functionality as you wish.
type contractsDao struct {
	internalContractsDao
}

var (
	// Contracts is globally public accessible object for table contracts operations.
	Contracts = contractsDao{
		internal.NewContractsDao(),
	}
)

// Fill with you ideas below.
