// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalFollowOrShieldUserRelationDao is internal type for wrapping internal DAO implements.
type internalFollowOrShieldUserRelationDao = *internal.FollowOrShieldUserRelationDao

// FollowOrShieldUserRelationDao is the data access object for table forum_follow_or_shield_user_relation.
// You can define custom methods on it to extend its functionality as you wish.
type FollowOrShieldUserRelationDao struct {
	internalFollowOrShieldUserRelationDao
}

var (
	// FollowOrShieldUserRelation is globally public accessible object for table forum_follow_or_shield_user_relation operations.
	FollowOrShieldUserRelation = FollowOrShieldUserRelationDao{
		internal.NewFollowOrShieldUserRelationDao(),
	}
)

// Fill with you ideas below.
