// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalHealthRecordDao is internal type for wrapping internal DAO implements.
type internalHealthRecordDao = *internal.HealthRecordDao

// healthRecordDao is the data access object for table health_record.
// You can define custom methods on it to extend its functionality as you wish.
type healthRecordDao struct {
	internalHealthRecordDao
}

var (
	// HealthRecord is globally public accessible object for table health_record operations.
	HealthRecord = healthRecordDao{
		internal.NewHealthRecordDao(),
	}
)

// Fill with you ideas below.
