// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalLoseBlocksDao is internal type for wrapping internal DAO implements.
type internalLoseBlocksDao = *internal.LoseBlocksDao

// loseBlocksDao is the data access object for table lose_blocks.
// You can define custom methods on it to extend its functionality as you wish.
type loseBlocksDao struct {
	internalLoseBlocksDao
}

var (
	// LoseBlocks is globally public accessible object for table lose_blocks operations.
	LoseBlocks = loseBlocksDao{
		internal.NewLoseBlocksDao(),
	}
)

// Fill with you ideas below.
