// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalNetworksDao is internal type for wrapping internal DAO implements.
type internalNetworksDao = *internal.NetworksDao

// networksDao is the data access object for table networks.
// You can define custom methods on it to extend its functionality as you wish.
type networksDao struct {
	internalNetworksDao
}

var (
	// Networks is globally public accessible object for table networks operations.
	Networks = networksDao{
		internal.NewNetworksDao(),
	}
)

// Fill with you ideas below.
