// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalQueueTaskDao is internal type for wrapping internal DAO implements.
type internalQueueTaskDao = *internal.QueueTaskDao

// queueTaskDao is the data access object for table queue_task.
// You can define custom methods on it to extend its functionality as you wish.
type queueTaskDao struct {
	internalQueueTaskDao
}

var (
	// QueueTask is globally public accessible object for table queue_task operations.
	QueueTask = queueTaskDao{
		internal.NewQueueTaskDao(),
	}
)

// Fill with you ideas below.
