// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalQueueTaskLogDao is internal type for wrapping internal DAO implements.
type internalQueueTaskLogDao = *internal.QueueTaskLogDao

// queueTaskLogDao is the data access object for table queue_task_log.
// You can define custom methods on it to extend its functionality as you wish.
type queueTaskLogDao struct {
	internalQueueTaskLogDao
}

var (
	// QueueTaskLog is globally public accessible object for table queue_task_log operations.
	QueueTaskLog = queueTaskLogDao{
		internal.NewQueueTaskLogDao(),
	}
)

// Fill with you ideas below.
