// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalThanksOrShieldOrCollectContentRelationDao is internal type for wrapping internal DAO implements.
type internalThanksOrShieldOrCollectContentRelationDao = *internal.ThanksOrShieldOrCollectContentRelationDao

// ThanksOrShieldOrCollectContentRelationDao is the data access object for table forum_thanks_or_shield_or_collect_content_relation.
// You can define custom methods on it to extend its functionality as you wish.
type ThanksOrShieldOrCollectContentRelationDao struct {
	internalThanksOrShieldOrCollectContentRelationDao
}

var (
	// ThanksOrShieldOrCollectContentRelation is globally public accessible object for table forum_thanks_or_shield_or_collect_content_relation operations.
	ThanksOrShieldOrCollectContentRelation = ThanksOrShieldOrCollectContentRelationDao{
		internal.NewThanksOrShieldOrCollectContentRelationDao(),
	}
)

// Fill with you ideas below.
