// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalTransactionDao is internal type for wrapping internal DAO implements.
type internalTransactionDao = *internal.TransactionDao

// transactionDao is the data access object for table transaction.
// You can define custom methods on it to extend its functionality as you wish.
type transactionDao struct {
	internalTransactionDao
}

var (
	// Transaction is globally public accessible object for table transaction operations.
	Transaction = transactionDao{
		internal.NewTransactionDao(),
	}
)

// Fill with you ideas below.
