// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalUserAddressesDao is internal type for wrapping internal DAO implements.
type internalUserAddressesDao = *internal.UserAddressesDao

// userAddressesDao is the data access object for table user_addresses.
// You can define custom methods on it to extend its functionality as you wish.
type userAddressesDao struct {
	internalUserAddressesDao
}

var (
	// UserAddresses is globally public accessible object for table user_addresses operations.
	UserAddresses = userAddressesDao{
		internal.NewUserAddressesDao(),
	}
)

// Fill with you ideas below.
