// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/app/dao/internal"
)

// internalWithdrawsDao is internal type for wrapping internal DAO implements.
type internalWithdrawsDao = *internal.WithdrawsDao

// withdrawsDao is the data access object for table withdraws.
// You can define custom methods on it to extend its functionality as you wish.
type withdrawsDao struct {
	internalWithdrawsDao
}

var (
	// Withdraws is globally public accessible object for table withdraws operations.
	Withdraws = withdrawsDao{
		internal.NewWithdrawsDao(),
	}
)

// Fill with you ideas below.
