// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package define

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

const (
	// 上下文变量存储键名，前后端系统共享
	ContextKey = "ContextKey"
)

// 请求上下文结构
type Context struct {
	Session       *ghttp.Session        // 当前Session管理对象
	Administrator *ContextAdministrator // 上下文用户信息
	Data          g.Map                 // 自定KV变量，业务模块根据需要设置，不固定
}

// 请求上下文中的用户信息
type ContextAdministrator struct {
	Id       uint   // 用户ID
	Username string // 用户账号
	Nickname string // 用户名称
	Avatar   string // 用户头像
}
