// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BlocksDao is the data access object for table blocks.
type BlocksDao struct {
	table   string        // table is the underlying table name of the DAO.
	group   string        // group is the database configuration group name of current DAO.
	columns BlocksColumns // columns contains all the column names of Table for convenient usage.
}

// BlocksColumns defines and stores column names for table blocks.
type BlocksColumns struct {
	Id       string //
	Number   string // 区块号
	Hash     string // 区块hash
	ChainId  string //
	CreateAt string // 创建时间
	UpdateAt string // 更新时间
}

//  blocksColumns holds the columns for table blocks.
var blocksColumns = BlocksColumns{
	Id:       "id",
	Number:   "number",
	Hash:     "hash",
	ChainId:  "chain_id",
	CreateAt: "create_at",
	UpdateAt: "update_at",
}

// NewBlocksDao creates and returns a new DAO object for table data access.
func NewBlocksDao() *BlocksDao {
	return &BlocksDao{
		group:   "default",
		table:   "blocks",
		columns: blocksColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BlocksDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BlocksDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BlocksDao) Columns() BlocksColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BlocksDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BlocksDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BlocksDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
