// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FollowOrShieldUserRelationDao is the data access object for table forum_follow_or_shield_user_relation.
type FollowOrShieldUserRelationDao struct {
	table   string                            // table is the underlying table name of the DAO.
	group   string                            // group is the database configuration group name of current DAO.
	columns FollowOrShieldUserRelationColumns // columns contains all the column names of Table for convenient usage.
}

// FollowOrShieldUserRelationColumns defines and stores column names for table forum_follow_or_shield_user_relation.
type FollowOrShieldUserRelationColumns struct {
	Id             string //
	UserId         string // 用户id
	Username       string // 用户名
	TargetUserId   string // 被关注｜屏蔽用户id
	TargetUsername string // 被关注｜屏蔽用户名
	Type           string // 类型 关注: follow,屏蔽: shield
	CreatedAt      string // 创建时间
}

//  FollowOrShieldUserRelationColumns holds the columns for table forum_follow_or_shield_user_relation.
var followOrShieldUserRelationColumns = FollowOrShieldUserRelationColumns{
	Id:             "id",
	UserId:         "user_id",
	Username:       "username",
	TargetUserId:   "target_user_id",
	TargetUsername: "target_username",
	Type:           "type",
	CreatedAt:      "created_at",
}

// NewFollowOrShieldUserRelationDao creates and returns a new DAO object for table data access.
func NewFollowOrShieldUserRelationDao() *FollowOrShieldUserRelationDao {
	return &FollowOrShieldUserRelationDao{
		group:   "default",
		table:   "forum_follow_or_shield_user_relation",
		columns: followOrShieldUserRelationColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FollowOrShieldUserRelationDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FollowOrShieldUserRelationDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *FollowOrShieldUserRelationDao) Columns() FollowOrShieldUserRelationColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *FollowOrShieldUserRelationDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FollowOrShieldUserRelationDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FollowOrShieldUserRelationDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
