// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// LoseBlocksDao is the data access object for table lose_blocks.
type LoseBlocksDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns LoseBlocksColumns // columns contains all the column names of Table for convenient usage.
}

// LoseBlocksColumns defines and stores column names for table lose_blocks.
type LoseBlocksColumns struct {
	Id       string //
	Number   string // 区块号
	Status   string // 检测状态，1已检测，0未检测
	CreateAt string // 创建时间
	UpdateAt string // 更新时间
}

//  loseBlocksColumns holds the columns for table lose_blocks.
var loseBlocksColumns = LoseBlocksColumns{
	Id:       "id",
	Number:   "number",
	Status:   "status",
	CreateAt: "create_at",
	UpdateAt: "update_at",
}

// NewLoseBlocksDao creates and returns a new DAO object for table data access.
func NewLoseBlocksDao() *LoseBlocksDao {
	return &LoseBlocksDao{
		group:   "default",
		table:   "lose_blocks",
		columns: loseBlocksColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *LoseBlocksDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *LoseBlocksDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *LoseBlocksDao) Columns() LoseBlocksColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *LoseBlocksDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *LoseBlocksDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *LoseBlocksDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
